name: Static Analysis
on: [pull_request]
jobs:
  style-and-bugs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
      distribution: temurin
      java-version: '17'
    - name: Maven verify (Checkstyle + SpotBugs)
      run: mvn -q -B -DskipTests verify