name: Build
on: [pull_request]
jobs:
  build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      distribution: temurin
      java-version: '17'
    - name: Build (compile & tests if present)
      run: mvn verify
